language: node_js

cache: npm

services:
  - mysql

env:
  global:
    - DATABASE_PORT=3306
    - DATABASE_NAME=blog
    - DATABASE_USERNAME=root
    - DATABASE_PASSWORD=""
  
before_install:
  mysql -e 'CREATE DATABASE blog'


install:
  - cd api
  - npm install newman
  - npm ci

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - npm run start &


script:
  - node_modules/.bin/newman run tests/Blog.js.postman_collection.json 